med=function(elements)
{
  elements=elements[order(elements)]
  if(length(elements)%%2==0)
  {
    n=length(elements)%/%2
    element=(elements[n]+elements[n+1])/2
  }
  else
  {
    element=elements[length(elements)%/%2+1]
  }
  return(element)
}
